version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: phpunit
    volumes:
      - ../:/usr/src/app
    environment:
      - PHP_EXTENSIONS=intl pdo_sqlite sqlite3
      - STARTUP_COMMAND_1=composer install
      - STARTUP_COMMAND_2=bash test/reset_tests.sh
      - PHP_IDE_CONFIG="serverName=propel"
  db:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./data:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
#  DEBUG VERSION
#  php:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    working_dir: /usr/src/app
#    command: phpunit --debug
#    volumes:
#      - ../:/usr/src/app
#    environment:
#      - PHP_EXTENSIONS=intl pdo_sqlite sqlite3 xdebug
#      - STARTUP_COMMAND_1=composer install
#      - STARTUP_COMMAND_2=bash test/reset_tests.sh
#      - PHP_IDE_CONFIG="serverName=propel"
#      - XDEBUG_MODE=debug
#      - XDEBUG_SESSION=1